# Generated by Django 4.0.2 on 2022-04-02 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_book_biography_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='uid',
            new_name='id',
        ),
    ]
